/*
  Copyright (c) 2012 Björn Esser

  Permission is hereby granted, free of charge, to any person obtaining
  a copy of this software and associated documentation files (the
  "Software"), to deal in the Software without restriction, including
  without limitation the rights to use, copy, modify, merge, publish,
  distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be
  included in all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT
  SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
  DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
  OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
  THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/


/*-/

  File:   Libyui_config.h

  Author: autogenerated by CMake

/-*/

#ifndef Libyui_CONFIG_H
#define Libyui_CONFIG_H

#define DATADIR		"/usr/local/Cellar/libyui"
#define DATAROOTDIR	"/usr/local/Cellar/libyui"
#define HELP_ICONS_DIR	"/usr/local/Cellar/libyui/images"
#define LANG_FONTS_FILE	"/usr/local/Cellar/libyui/data/lang_fonts"
#define LOCALEDIR	"/usr/share/locale"
#define PLUGINDIR	"/usr/local/lib"
#define THEMEDIR	"/usr/local/Cellar/libyui/theme"
#define PLUGIN_PREFIX	"libyui-"
#define PLUGIN_SUFFIX	".8"
#define LIBYUI_VERSION_NUM (((3) << 16) | ((3) << 8) | (3))
#define LIBYUI_VERSION_AT_LEAST(M,N,O) LIBYUI_VERSION_NUM >= (((M) << 16) | ((N) << 8) | (O))

#endif // Libyui_CONFIG_H
